import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import LangChoice from '@/components/LangChoice'
import { useState } from 'react'
import { Typography } from '@mui/material'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [lang, setLang] = useState('python')

  return (
    <>
      <Head>
        <title>C4</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main + " w-screen relative overflow-clip"}>

        <div className={styles.center + " w-screen h-full absolute  "}>
          {/* <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          /> */}
        </div>
        <div className={styles.thirteen + " w-[60vw] h-[60vh] max-w-6xl flex flex-col align-top "}>
          <Typography>
            <span
              className='text-3xl text-sky-300 w-40 justify-center uppercase'
            >
              {lang}
            </span>
          </Typography>
          <div
            className='mt-20'
          >
            <LangChoice lang={lang} setLang={setLang} />
          </div>
          {/* <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            /> */}
        </div>

      </main>
    </>
  )
}
